.gitignore, PUBLISHING.md, README.md, imgs/README.md, imgs/awsutils/default.nix, nwi.nix, pin/pins/nixos-unstable_0.json, publish-imgs, shell.nix
There is no way to take the existing `awsutils` container and cleanly publish it to a registry. Additionally since we are using the derivations for the image tags we have no way of identifying what versions of pkgs are contained in the container without running it.
* image push script
* adding unstable pin to use the newest version of skopeo
* pkg versions be included in image as label: `com.nebulaworks.packages`
Current `awsutils` image published to our dockerhub registry:
```
$ skopeo inspect docker://docker.io/nebulaworks/awsutils:dz783iaashdby6phqf9pcydxsw1bbjq0
{
"Name": "docker.io/nebulaworks/awsutils",
"Digest": "sha256:4df34c1e6ab561b3aa6f0c250122ce121ff18e6803d72733f041978b87979df4",
"RepoTags": [
"dz783iaashdby6phqf9pcydxsw1bbjq0"
],
"Created": "1970-01-01T00:00:01Z", …
```
=> Adding image labels and publishing

README.md, isos/README.md, isos/yubikey/README.md, isos/yubikey/default.nix
This PR adds the following functionality to the repository:
- A `.nix` config that defines all of the requirements Nebulaworks needs to create a Yubikey NixOS image.
- A `README.md` that documents out the process for making the LiveCD.
- Verified that the image can be created via the command outlined in the `README.md`
- Used VM software to boot up the `.iso` and confirmed all needed packages are on the image.
=> [READY] Added LiveCD Configuration for Yubikey NixOS

default.nix, pkgs/flasksample/default.nix
Adding `flasksample` derivation for use and testing of http endpoints. Leveraging a branch from the fork of https://github.com/sjeeva/flaskapp. Will eventually move this into a more perment location within the NWI org.
* Able to build the `flasksample` derivation with `nix-build`
* Able to run flask application inside temporary nix-shell:
```
~$ nix-shell -p "with import ./default.nix {}; flasksample"
```
Inside nix-shell:
```
[nix-shell:~/nix-garage]$ export FLASK_APP=flasksample.app
[nix-shell:~/nix-garage]$ flask run &
[1] 4503
[nix-shell:~/nix-garage]$  * Serving Flask app "flasksample.app"
* Environment: production
WARNING: This is a development server. Do not use it in a production deployment.
Use a production WSGI server instead.
* Debug mode: off
* Running on …
```
=> [READY] Adding flasksample pkg and toplevel default.nix

.github/workflows/publish_imgs.yml
This PR adds in a new CI/CD workflow in the `nix-garage` repository where images defined via `nix` in `imgs/` can be automatically built and published to Nebulaworks's Docker Hub page.
To utilize the new job, the following workflow has been established (feedback is welcome!)
1. A contributor creates some new changes/adds a new image in the `img/` folder.
2. The contributor pushes their code up and opens a new PR to the master repository
3. After reviewing the new code, a person from Nebulaworks's `approvers` team can kick off a CI job by commenting in the PR:  `publish` (as of now, any words after `publish` is ignored, but the first word of the comment _must_ be `publish`) 
4. After a few minutes, a bot account (in this case, `nwiauto`) will automatically comment on that same PR, saying …
=> [READY] Added workflow for publishing Docker images via CI/CD

.github/workflows/lint-nix.yml, .github/workflows/publish_imgs.yml
This PR fixes an issue with the workflow files in that they were missing a key parameter to make sure that they were pulling code from the _PR_, not from the default branch. Also, some minor clean up was done on the workflow files in order to keep consistency as well as clarity.
Note: The `lint-nixpkgs` job still worked as intended because it was using a PR event, which the default action for `actions/checkout` in that case is to use the PR's head commit. This isn't the case for the `publish_imgs`, which uses an issue_comment event. As such, to keep consistency, the `lint_nixpkgs` is also modified to reflect the specific usage of a branch SHA.
The issue of the authentication error comes from the context that the event was running from. Because of the default behavior of …
=> [READY] Fixed workflows to utilize proper checkout parameters

.github/workflows/publish_imgs.yml
After noticing `publish` failures it looks like we were expecting the wrong secret credential. These was an oversight while testing some new features of our actions workflow. This should fix things.
=> [READY] Using actual secret ref

imgs/awsutils/default.nix
`curl` isnt very useful if you dont have a certificate authority. Got the follow error due to no ca trusts being present:
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
=> [READY] - Adding cacert pkg to awsutils img

imgs/magic-wormhole-mailbox/README.md, imgs/magic-wormhole-mailbox/default.nix
This PR adds in a new `docker image` configuration that automatically sets up a self-hosted rendezvous server for a magic-wormhole service. 
Since there are little open sourced solutions to building consistent solutions in running self-hosted solutions, I think this can greatly help others see a working example of this and how they can implement this in their own solutions.
- Build derivation successfully and imported docker image
- Ran container and tested service locally
=> [READY] Added config for magic-wormhole-mailbox

.github/workflows/publish_imgs.yml, PUBLISHING.md, README.md, create-repo, imgs/awsutils/README.md, imgs/helmsman-aws/README.md, imgs/magic-wormhole-mailbox/README.md, shell.nix, templates/README.md, templates/README_imgs.tpl
This PR continues to improve on the `publish-imgs` GitHub Action workflow by now auto-creating any new Docker Hub repository when a new image is being published for the first time.
In order to facilitate this workflow, the following new items are added to the repository:
1. A `templates/` directory which contains the following:
- A `README_imgs.md`, which outlines a standardized `README` for all images made in this repository
- A `README.md`, explaining the purpose and usage of the templates in that directory 
2. A new script, `create-repo`, which facilitates the creation of a new Docker Hub repo via API calls
- This script also does the following:
- Adds in the `engineering` group with `read/write` permissions
- Adds in both a `short_description` and a `long_description`, with them being …
=> [READY] Auto-Repo Creation via GitHub Workflow

imgs/pki-validator/README.md, imgs/pki-validator/default.nix
This PR adds in another Docker image to the repo, `pki-validator`. This image is designed to be used to run test cases with `openssl` and `make`.
=> [READY] Added pki-validator Image

README.md, pin/generate_pin
nixos branches use a `.` not at `-`. attempting to pin with the `-` fails
https://github.com/NixOS/nixpkgs-channels/tree/nixos-20.03
=> fix help docstring for specifying a different branch

.github/workflows/publish_imgs.yml, README.md, default.nix, imgs/awsutils/default.nix, imgs/default.nix, imgs/helmsman-aws/default.nix, imgs/magic-wormhole-mailbox/default.nix, imgs/pki-validator/default.nix, overlay.nix, publish-imgs
We should be leveraging an overlay and organizing our nix packages in a more clear manner. This should start us down that path
* Images still build as expected
* Anyone can consume overlay.nix from this repo
Using the new overlay. I had to leverage my branch but once we merge this into `master` we can leverage it via what I added in the README:
A sample `shell.nix`:
```nix
let
nix-garage = builtins.fetchGit {
url = "https://github.com/sarcasticadmin/nix-garage";
ref = "sa/gl-issue-309";
};
garage-overlay = import (nix-garage.outPath + "/overlay.nix");
nixpkgs = import <nixpkgs> { overlays = [ garage-overlay ]; };
in
with nixpkgs;
mkShell {
buildInputs = [
flasksample
];
}
```
Then drop into the nix-shell and run the `flasksample` pkg:
```bash
$ nix-shell
[nix-shell] $ export …
```
=> [READY] - Reworking default.nix and adding overlay

.github/pull_request_template.md, overlay.nix, pkgs/sshcb/default.nix
Adding `sshcb` to our overlay as its something that we leverage when needing to build an ssh_config using EC2metadata
`sshcb` builds:
```
$ nix-build -A pkgs.sshcb
/nix/store/inikz4fkpxmyaygzwcjw61wvaf8dygrp-sshcb-0.2.1
```
`sshcb` works as expected:
```
$ nix-shell -p "with import ./default.nix {}; pkgs.sshcb"
[nix-shell:~/nix-garage]$ sshcb version
v0.2.1
```
=> [READY] - sshcb init 0.2.1

imgs/awsutils/default.nix
awsutils needs git-lfs, tar and gzip installed in order to properly backup lfs repos.
awsutils builds:
```
nix-build -A imgs.utils
/nix/store/c3skllz0pvp6a78nf3c4fck7xcg1yxq5-docker-image-awsutils.tar.gz
```
awsutils works as expected:
```
docker run -it nebulaworks/awsutils:latest /bin/sh
sh-4.4# tar --version
tar (GNU tar) 1.32
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by John Gilmore and Jay Fenlason.
sh-4.4# gzip --version
gzip 1.10
Copyright (C) 2018 Free Software Foundation, Inc.
Copyright (C) 1993 Jean-loup Gailly.
This is free software.  You may redistribute copies of …
```
=> [READY] add git-lfs, tar and gzip to awsutils img

.github/workflows/lint-nix.yml, .github/workflows/publish_imgs.yml, pkgs/sshcb/default.nix
Running `nix-build` for `sshcb` was broken in the current version of Nix. To fix this:
* Standardized the imports to `nixpkgs`.
* Fix `modSha256` to `vendorSha256` with the current checksum.
* `stdenv.lib` -> `lib`
It was borked.
It's not borked anymore.
Tested in a Vagrant box - 20.04 with the current version of Nix. Successfully ran `nix-build` and verified the built executable worked.
=> [READY] do/issue-419: fix sshcb nix build

overlay.nix, pkgs/aws-key-rotator/default.nix
Make a `nix` build for `aws-key-rotator`.
Tested in my VM. Successfully built with `nix build -A pkgs.aws-key-rotator` and successfully ran it.
=> [READY] do/issue-421: add aws-key-rotator nix build

overlay.nix, pkgs/terraform-config-inspect/default.nix
Creating a new nix build for `terraform-config-inspect`. Also tested building with Cachx and pushed the binaries up.
The main caveat was that I had to fork the original repo in order to add a tag and create a version, as the original repo only has a `master` branch and no tags at all.
Fork: https://github.com/davido-nw/terraform-config-inspect
Original: https://github.com/hashicorp/terraform-config-inspect
The version I created was basically just today's timestamp.
- Built locally.
=> [READY] do/issue-436: add terraform-config-inspect nix build

pkgs/flasksample/default.nix
Requires: https://github.com/Nebulaworks/orion/pull/1
No longer need to reference my random fork for this code, but instead it can now be found as part of `orion`
- Leveraged @sarcasticadmin fork for flasksample project
- Needed to `export FLASK_APP=flasksample.app` env variable before running `flask run`
- Leverage sample app in `orion`
- Created entry_point to be able to run application by name: `flasksample`
building pkgs works:
```
$ nix-build -A pkgs.flasksample
these derivations will be built:
/nix/store/dalnpxnl8gvgbnqman554yark627vsca-python3.8-flasksample-0.1.0.drv
building '/nix/store/dalnpxnl8gvgbnqman554yark627vsca-python3.8-flasksample-0.1.0.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh …
```
=> [READY] - Updating reference for flasksample

.github/workflows/lint-nix.yml, .github/workflows/publish_imgs.yml
Were getting an error: 
```
for currImgPath in $(ls -d $GITHUB_WORKSPACE/imgs/*/)
++ basename /__w/nix-garage/nix-garage/imgs/flasksample/
+ currImgName=flasksample
+ '[' -z awsutils ']'
+ allImgs='awsutils, flasksample'
+ set +x
Docker Hub repo flasksample does not exist in nebulaworks, creating now...
{"user": "nebulaworks", "name": "flasksample", "namespace": "nebulaworks", "repository_type": null, "status": 0, "description": "", "is_private": false, "is_automated": false, "can_edit": true, "star_count": 0, "pull_count": 0, "last_updated": null, "is_migrated": false, "collaborator_count": 0, "affiliation": "owner", "hub_user": "nwiauto", "full_description": ""}
User is actually organization, attempting to add engineering group with read/write permissions in repo flasksample... …
```
=> [READY] - Bump nix ci container to v2.3.12

imgs/default.nix, imgs/flasksample/README.md, imgs/flasksample/default.nix, pkgs/flasksample/default.nix
Requires: #31 
Now that we have `flasksample` in orion, lets make a container for running it.
- No container for `flasksample` existed outside of the one for the originator
- We can now build our fork of `flasksample` and put it into a container
- Publish flasksample to dockerhub
CI built image successfully: https://github.com/Nebulaworks/nix-garage/runs/3033686285?check_suite_focus=true
Pulling it down locally and running it:
```
$ docker run -it -p 5000:5000 nebulaworks/flasksample:kxhq2jcijnkp8qhnlhy47023jcd0rj52
* Serving Flask app "flasksample.app" (lazy loading)
* Environment: production
WARNING: This is a development server. Do not use it in a production deployment.
Use a production WSGI server instead.
* Debug mode: off
* Running on http://0.0.0.0:5000/ (Press CTRL+C to quit) …
```
=> [READY] - Adding flasksample container to our list of imgs

default.nix, imgs/default.nix, imgs/helmsman-aws/default.nix, imgs/magic-wormhole-mailbox/default.nix, isos/yubikey/default.nix, overlay.nix, pin/default.nix, pin/generate_pin, pin/pins/nixos-unstable_0.json, pin/pins/release-21.05_0.json, pkgs/codefresh/yarn.nix, shell.nix
The `nix-shell` pin has quite old and needs to be updated before we do any further work on unpinning the imgs we are building. This is to check to see how reproducible out results are given updates in the tool chain. I suspect for what we are leveraging it will be minimal but want to see how it behaves while we have the opportunity.
- Pin for nix-shell was point to old pin that came for now deprecated nix channel repo
- Pin point to latest release branch 21.05
- nixpkgs-fmt has new requirements that needed to be accounted for: `find . -name "*.nix"| xargs nixpkgs-fmt`
- `publish` to see how the imgs build inside this new `nix-shell`
- Results `publish` of imgs remained stable as expected: 
`flasksample` - https://github.com/Nebulaworks/nix-garage/runs/3146948986?check_suite_focus=true#step …
=> [READY] - Updating pins for toplevel nix-shell 

.github/workflows/daily.yml, .github/workflows/publish_imgs.yml, publish-imgs
We can now enable building out container images daily off of the upstream nixpkgs. This will allow us to have very up to date images published to dockerhub without us having to bump pins, etc.
In addition to these changes I have updated some of the other scripts and workflows to help simplify there function and leverage some the functionality thats built into `nix` (`nix-instantiate` for example)
- No daily container image builds were happening in our workflows
- `publish_imgs` workflow we were leveraging file names instead of nix attributes
- `publish_imgs` workflow returns all images for every run via comment
- Leverage nix path attributes for `publish_imgs` in the case where we have multiple images that come from a single drv (not the case yet but absolutely possible in the future)
- …
=> [READY] - Enable daily builds of our container images

.github/workflows/daily.yml
`publish-imgs.sh` should be `publish-imgs`
- Wrong file name
- Correct file name
- Run workflow via dispatch
=> [REVIEW] - Correct file path for publish-imgs daily

.github/workflows/daily.yml
We were missing auth... Of course!
- `daily` build workflow failed due to missing `auth.json`:  https://github.com/Nebulaworks/nix-garage/runs/3510324797?check_suite_focus=true
- Now we have `auth.json` and can publish to docker hub: https://github.com/Nebulaworks/nix-garage/runs/3510354593
- Also confirmed that are still only pushing images we have already built: https://github.com/Nebulaworks/nix-garage/actions/runs/1199583937
- `Daily workflow` success and resulting in newly images published to dockerhub:
```
awsutils:hx1a61jwx4r2crri7iph7ygd19gbqab5,flasksample:zzpm4r45shaicn75lgvlnhxfqk3rgm9x,helmsman-aws:paks7yd7laypwmpg3i3mbvw937hdgdnc,magic-wormhole-mailbox:lizc5jamh39zy5xm4cjhnd3a9v3gxzm9,pki-validator:s1l8jmzblv13rnzs9ggsd2xrssalj52a
```
=> [READY] Adding missing auth for daily build

overlay.nix, pkgs/git-divergence/default.nix
Needed to use https://github.com/Nebulaworks/orion/tree/main/scripts/git_divergence for something and wanted it installed via nixpkgs :slightly_smiling_face: 
- `git_divergence` didnt exist in nix-garage as a nixpkg
- `git_divergence` exists in the nix-garage overlay :partying_face: 
- Tested again this repo:
```
$ nix-shell -p "with import ./default.nix {}; pkgs.git-divergence"
$ GIT_REPO_PATH=. divergence                                            
Repo at . successfully loaded.                     
Repo description: Unnamed repository; edit this file 'description' to name the repository.
Remote named "upstream" with URL "git@github.com:Nebulaworks/nix-garage.git"
Branch                    Behind   Ahead   DSB  DSLC DIVERGENCE …
```
=> [READY] - Init git-divergence from orion

README.md, RELEASE.md, pin/generate_pin, pin/pins/master_0.json, pin/update_release, publish-imgs, release.nix
Considering we are daily building our containers: https://github.com/Nebulaworks/nix-garage/actions/workflows/daily.yml
We need a way to point to the last successful build of our containers for a release
- No automated way to update `release.nix`
- Run `update_release` to get latest daily build results from github action
- Update the refs accordingly for pin and release.nix
- Updated `publish-imgs` to support more than just `default.nix` toplevel
- Initialized release docs
- pr comment image build returns no new results since we already built them off previous daily build :)
- `./publish-imgs -f release.nix -s imgs` Confirms thats theres no publishing necessary :)
```
{
"Name": "docker.io/nebulaworks/awsutils",
"Digest": "sha256:b767d0070b5136f7576f222c4b01c00cb0bb1aa5241c3fd598477c0b480e3 …
```
=> [READY] - Update release.nix automatically based on daily build results

.github/workflows/daily.yml, publish-imgs
Fixes: #43
Publishing new imgs to the registry seem to be broken after #41 
```
$ nix-shell --run 'bash -x ./publish-imgs'
...
+ calcout='"/nix/store/0q6n72i9f6w35qg70a8fddnh57jr25yb-docker-image-awsutils.tar.gz"'                                                                                                                              
++ basename '"/nix/store/0q6n72i9f6w35qg70a8fddnh57jr25yb-docker-image-awsutils.tar.gz"'                                                                                                                            
++ cut -d - -f1                                                                                                                                                                                                     
+ …
```
=> [READY] - [ ISSUE-43 ] - Fixing entry reference for publish-imgs

imgs/default.nix, imgs/nwi-pr-utils/README.md, imgs/nwi-pr-utils/default.nix
Creating a new image with `yamllint` and `tfsec`. This can be a base image for generic tools that run during our internal repos' CI. I know we needed to create a `yamllint` image anyway to accommodate that tool, but I figure why not assimilate a few other tools under our control and have nix build that image?
Testing the build in this PR, then will test this image with the private infra repo's PR.
=> [READY] - [do/issue-456] create nwi-pr-utils image with tfsec and yamllint

imgs/nwi-pr-utils/default.nix
The `tfsec` installation in the `nwi-pr-tools` image didn't work as intended. There was a typo in the `contents` line, and it turns out we probably don't need the overridden `goPackagePath` and `ldflags` attributes.
=> [READY] - fix nwi-pr-tools tfsec installation

imgs/nwi-pr-utils/default.nix
fixes #47 
- The github.com/tfsec/tfsec repo references no longer resolve.
- The new repo url is github.com/aquasecurity/tfsec.
- These unresolvable go dependencies break the nix build.
- After our downstream CI has been updated to utilize v0.63.1 (latest) tfsec release, we can merge this PR to fix the broken nix-garage daily build.
daily build is broken: https://github.com/Nebulaworks/nix-garage/runs/4913402701?check_suite_focus=true#step:4:707
Fixes build
=> [READY] - update tfsec to latest release

imgs/default.nix, imgs/term-apply/default.nix, overlay.nix, pkgs/term-apply/default.nix, shell.nix
Relates to: https://github.com/Nebulaworks/orion/pull/7
Init term-apply pkg and image to nix-garage for general usage: sshapply.nebulaworks.com
The process of applying is as simple as sshing and filling out the form presented via your ssh session:
```
ssh <github_user>@sshapply.nebulaworks.com
```
`scp` your resume to the server as well:
```
scp -P 23234 <resume>.pdf <github_user>@sshapply.nebulaworks.com:resume.pdf
```
> Note: your ssh key needs to be associated with the same github_user your are passing
- term-apply available via nixpkg overlay and img artifact
- Unit tests running for `term-apply`
- `publish` builds and pushed to dockerhub: https://github.com/Nebulaworks/nix-garage/actions/runs/2080355450
- CA cert bundlers included in container after:
```
Of course I need to include …
```
=> [READY] - Init term-apply pkg and img

.github/workflows/daily.yml, .github/workflows/lint-nix.yml, .github/workflows/publish_imgs.yml, pin/default.nix, pin/pins/master_0.json, pkgs/term-apply/default.nix, publish-imgs, shell.nix
Daily container build thats checking nixpkgs upstream is failing: https://github.com/Nebulaworks/nix-garage/actions/runs/2116049726
- We were referencing older pins from 2021 nixpkgs
- v2 actions checkout
- Leverage a pin `nix-shell` tools calling in CI workflow during img build
- Fix reference from pin to point to n`ixpkgs` instead of deprecated `nix-channels`
- switching to v1 actions checkout since it doesnt depend on javascript and `/etc/os_release` (open issue from 2020): https://github.com/actions/checkout/issues/334
- Move the linting action to encompass entire `nix-shell` vs only oneliner 
- Running `nix-build` locally with updates passes as expected
- Triggered the daily dispatch: https://github.com/Nebulaworks/nix-garage/actions/runs/2174432446 but cant actually run the publish …
=> [READY] - Fixing daily img build and update pinning

.github/workflows/publish_imgs.yml
Running into failures with having a newer version of the nix container + cachix. Runs into the same problems when have had historically with actions and node :slightly_frowning_face: 
- Cachix removed from publish_imgs workflow
- Publish_imgs workflow works with changes that were made in https://github.com/Nebulaworks/nix-garage/pull/51
- TBD
=> [READY] - Temporarily remove cachix from publishing

.github/workflows/publish_imgs.yml, GNUmakefile, PUBLISHING.md, ci.nix, pin/generate_pin, pin/pins/master_1.json, shell.nix
Fixes: #59 
- nixpkgs version was set to what was in the container which wasnt great
- nixpkgs referring to a newer pin from master
- `make test-publish` which doesnt effect the docker repositiories but checks to see if it needs to build any imgs:
```
./publish-imgs -s -f ci.nix
{
"Name": "docker.io/nebulaworks/awsutils",
"Digest": "sha256:0589df2c6c5593f088528a7c9dbb0921593684b6c3688c3af1c6f08a97d5fcd1",
"RepoTags": [
"062y3vxhs7hap0v279gy1wrcnmmnngy4",
"0afjz2x6jzlqbyp6hlsn7xx1j4v595xj",
"0q6n72i9f6w35qg70a8fddnh57jr25yb",
"0wrw13hq33i9lvliwgrilimblm1by6ga",
"1hx4387bjv85cs424znxr9fpbdbm8djk",
"43pax9ygdpviwka1lvqkvsxk3qlkg32i",
"4iyc3wm1kjz9lwqwsgvjz8g78hdgxc7p",
"4yzrc2fjyajqaihgn3jycfjjsrwrdb7z",
"5cnip2b81k71qbap8493mmvfp02fk6wh",
"5dq3sxqy6ql24adppr4abllkpq51ai25", …
```
=> [READY] - [issue-59] - init ci.nix and GNUmakefile

imgs/README.md, imgs/ansible-lint/README.md, imgs/ansible-lint/default.nix, imgs/default.nix, publish-imgs
Adds a new image for `ansible-lint` with some typical complementary tools such as `yamllint`, `pytest`, `pylint`, `jq`, `git`, etc. Immediate use case is for github actions in the CI workflow for [SCaLE network](https://github.com/socallinuxexpo/scale-network/blob/master/.github/workflows/ansible-test.yml). This method seems like a much better alternative to the "standard" [ansible lint github action](https://github.com/ansible/ansible-lint-action/) so others might find it useful. There's also an opportunity to add this to some existing internal projects.
```
$ nix-build -A imgs.ansible-lint
/nix/store/b3451xr827aasi99y97j52pnxl6gji5k-docker-image-ansible-lint.tar.gz
$ docker load < /nix/store/b3451xr827aasi99y97j52pnxl6gji5k-docker-image-ansible-lint.tar.gz
Loaded image: …
```
=> [READY] - add ansible-lint image

isos/yubikey/default.nix
Fixes: #62 
- Yubikey iso build was reference config and extra nixpkgs
- No pin for nixpkgs
- Removed uneeded nixpkg
- Updated config for the newer version of nixpkgs
- Pinning to nixpkgs to make it reproducible
- Locally was able to build:
```
$ cd isos/yubikey/
$ nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=default.nix --out-link installer                                                       
these 59 derivations will be built:                                                                                                                                                                                 
/nix/store/0rwkp1iflf0ignr1zrl1w49hyx61fi0n-kernel-modules.drv …
```
=> [READY] - Updates for offline yubikey iso build

create-repo
Fixes #52 
READMEs on Docker Hub will now be updated.
READMEs were only updated on Docker Hub when a repo was first created. Any changes were never reflected.
Updating READMEs has been moved to a function which is now called even if the repo already exists. I chose to do this in `create-repo` instead of `publish-images` (only when we build) because it would have been a bigger change. The only downside with this approach is we will post the README to DockerHub every time. Seemed like an OK tradeoff.
=> [READY] - [issue-52] - READMEs update for existing repos

pkgs/term-apply/default.nix
Bumps version of term-apply to target version referenced in https://github.com/Nebulaworks/orion/pull/11 (technically it targets the branch directly on origin with the same name given we shouldn't use forks for this)
term-apply pkg referenced previous version which lacked s3 support
term-apply pkg references new version with s3 support
=> [READY] - [issue-511] - bump term-apply pkg for s3 resume/csv support

pkgs/sshcb/default.nix
Fixes #58 
sshcb build now leverages `ldflags` instead of deprecated `buildFlagsArray`.
sshcb build leveraged `buildFlagsArray`
sshcb build now leverages `ldflags`
```
$ nix-build -A pkgs.sshcb
these 3 derivations will be built:
/nix/store/mfnp16nh5sajz4xswcd66dgz8xa3nl9l-source.drv
/nix/store/2s1nwk047araj5xcg2z54bh1x5c2b7lm-sshcb-0.2.1-go-modules.drv
/nix/store/851k4vgwspqfjggwwrhklw5r69f441hp-sshcb-0.2.1.drv
building '/nix/store/mfnp16nh5sajz4xswcd66dgz8xa3nl9l-source.drv'...
trying https://github.com/sarcasticadmin/sshcb/archive/v0.2.1.tar.gz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  8377    0  8377    0     0  14778      0 …
```
=> [READY] - [issue-58] - switch sshcb to build using ldflags

imgs/term-apply/README.md, pkgs/term-apply/default.nix
2022-05-13 release of term-apply
- log resume uploads past the first in term-apply -  [[o13](https://github.com/Nebulaworks/orion/pull/13)]
- environment variable parsing all handled in one place when creating new config [[o15](https://github.com/Nebulaworks/orion/pull/15)]
- s3 prefixes can be changed with environment variables - [[o15](https://github.com/Nebulaworks/orion/pull/15)]
- add README to term-apply [[o16](https://github.com/Nebulaworks/orion/pull/16)]
```
$ TA_UPLOAD_DIR=/tmp/uploads TA_BUCKET=test-bucket /nix/store/1yc3pzhjf3zfzmz1z07k1i645v36scyv-term-apply-unstable-2022-05-13/bin/term-apply 
2022/05/13 15:42:44 
Build Info:
===========
commit:      fb0b1491c68afca0e06703835f984b371e0571e6
build time:  01011970
2022/05/13 15:42:44 TA_HOST set to '0.0.0.0'
2022/05/13 15:42:44 …
```
=> [READY] - [issue 522] - term-apply 2022-05-13 release

imgs/magic-wormhole-mailbox/default.nix, pkgs/aws-key-rotator/default.nix, pkgs/flasksample/default.nix, pkgs/git-divergence/default.nix, pkgs/term-apply/default.nix, pkgs/terraform-config-inspect/default.nix, publish-imgs
Fixes: #69 
Relates: #64 
Fixing daily.yml since its been failing
- daily.yml failing
- Maintainers for all pkgs must be lists
- Remove minor version of python (upstream python3.7 is no more) plus its easier to leverage the nixpkg pins for consistency
- publish-imgs no longer leverages a subshell inline or has `set -e` 
Ran publish-imgs with fixes against broken `master`:
```
$ nix-shell --run 'bash ./publish-imgs'
error: value is a string while a list was expected
at /nix/store/b0db8fic9vxksg726bxzmrslpzsp87a5-source/pkgs/stdenv/generic/check-meta.nix:54:34:
53|   hasNoMaintainers = attrs:
54|     attrs ? meta.maintainers && (lib.length attrs.meta.maintainers) == 0;
|                                  ^
55|
(use '--show-trace' to show detailed location information)
parse error: Unmatched …
```
=> [READY] - Resuming daily build

pkgs/term-apply/default.nix
term-apply 2022-05-17 release
- The csvKey was being set to the s3 prefix + the full path of the TA_DATAFILE
- When uploading to s3 we never close the local file handle we open
- When a user submitted the form via SSH but hasn't yet uploaded a resume, the logs get spammed with "NotFound" every 5 seconds while they are logged in
- The csvKey is now being set to the filename in TA_DATAFILE and not the full path [[o17](https://github.com/Nebulaworks/orion/pull/17)]
- We now close the file handle we open to copy files to S3 [[o17](https://github.com/Nebulaworks/orion/pull/17)]
- We no longer unnecessarily log "NotFound" every five seconds when a user is connected who has submitted the form via SSH but has not yet SCP'd the resume [[o17](https://github.com/Nebulaworks/orion/pull/17)]
=> [READY] - [issue 531] - term-apply 2022-05-17 release

overlay.nix, pkgs/upgrade-eks-workers/default.nix
Adding in pkg from orion for upgrading eks workers: https://github.com/Nebulaworks/orion/blob/main/scripts/upgrade-eks-workers.sh
- pkg was no in overlay
- pkg is now in the overlay
- Script built and available in overlay:
```
$ nix-build -A pkgs.upgrade-eks-workers
$ ./result/bin/upgrade-eks-workers -h
Usage: REGION=<region> AWS_PROFILE=<profile> upgrade-eks-workers <cluster_name>
Upgrade EKS cluster worker nodes by draining and terminating a single instance at a time.
This script requires ~10.5min to cycle EKS worker nodes.
ENVIRONMENT VARIABLES REQUIRED:
REGION            the AWS region your cluster is deployed to
AWS_PROFILE       an AWS profile to access your cluster
EXAMPLE:
REGION=us-west-2 AWS_PROFILE=nwi-eks-admin ./upgrade-eks-workers.sh <cluster_name>
```
=> [READY] - init upgrade-eks-workers@08-31-2021

.github/workflows/daily.yml, imgs/magic-wormhole-mailbox/default.nix
Relates to:  https://github.com/NixOS/nixpkgs/issues/164775
There is an existing issues around daily build, see: https://github.com/Nebulaworks/nix-garage/actions/runs/2385446134
- Daily builds against nixpkgs `master` are failing due to twisted `dropin.cache` conflicts
- Disable twisted test until upstream `twisted` issues with `dropin.cache`
- Triggering a dispatch of the `daily workflow` works as expected: https://github.com/Nebulaworks/nix-garage/runs/6597588623
- Able to trigger a workflow via `publish` command: https://github.com/Nebulaworks/nix-garage/actions/runs/2399294622
- Able to build and run wormhole img successfully.
Against existing `pin` (https://github.com/Nebulaworks/nix-garage/actions/runs/2399294622):
```
$ docker run -it --rm …
```
=> [READY] - [issue-69] - Omit checks for magic-wormhole-relay temporarily

pkgs/term-apply/default.nix
Fixes: #512 in infra
Adds file validity checking for both size and file type
* Any uploaded file is accepted and uploaded to the s3 bucket
* File size is checked to ensure it isn't too large (greater than 10MB) files any larger are invalid
* File contents are analyzed to ensure it is actually a valid PDF
* Any file that is flagged as invalid is not uploaded to s3 or saved to the uploads folder of the server
* When an upload fails, the user is notified when their last valid file was uploaded, or if they have never uploaded a valid file.
* Two different files were uploaded: one plain text file and one pdf. Only the pdf was uploaded to s3
* A valid PDF that is greater than 10MB was uploaded and rejected immediately.
=> [READY] - [dh/infra-issue-512] Adds pdf validation to term-apply

pkgs/term-apply/default.nix
Fixes: [infra issue #524](https://gitlab.com/nebulaworks/eng/infra/-/issues/524) and [infra issue #539](https://gitlab.com/nebulaworks/eng/infra/-/issues/539)
Brief description of the PR
* Each time a new RE of term-apply was spun up, a new SSH host key would be generated, leading to inconsistency of host keys.
* Fatal error would occur if the `TA_HOST_KEY_PATH` contained a public key with no corresponding private key
* Host Keys can be downloaded from SSM SecureString Parameters specified by the `TA_SSM_HOST_KEY_PARAM` env variable.
* The location of host keys can be specified by the `TA_HOST_KEY_PATH` env variable.
* This location serves as the target download location for the key specified by `TA_SSM_HOST_KEY_PARAM` should a parameter be provided, the local location term-apply will …
=> [READY] - [dh/infra-issue-524/539] term-apply ssh host key consistency AND SIGSEGV with server error

pkgs/term-apply/default.nix
This updates the version of term-apply to the version from the corresponding branch in orion.
There was a race condition with reading and writing to DynamoDB.
A given applicant's record is locked while it's being updated.
I ran a build locally and it completed successfully.
=> [READY] [infra-529] Set new version info for term-apply

pkgs/terraform-config-inspect/default.nix
Relates to: https://github.com/Nebulaworks/nix-garage/pull/68
`buildFlagsArray` has been deprecated for some time. Moving the last reference of this in pkgs to `ldflags`
- Warning received anytime overlay is consumed due to `buildFlagsArray`
- Warning gone since all go pkgs leverage `ldflags`
- Build from the toplevel of this repo:
```
$ nix-build -A pkgs.terraform-config-inspect
$ ./result/bin/terraform-config-inspect -v
unknown shorthand flag: 'v' in -v
Usage of ./result/bin/terraform-config-inspect:
--json   produce JSON-formatted output
unknown shorthand flag: 'v' in -v
```
> not really any flags due to the nature of this codebase
=> [READY] - rm deprecated buildFlagsArray in tf config inspect pkg
